### ISSUE TITLE
[question] replace "foo\nbar" with real new line

### ISSUE THREAD

**Issue by ozbillwang** [atom/find-and-replace#1004]
### Description

I just want to replace the string `foo\nbar` to 

```
foo
bar

```
### Steps to Reproduce

1. search with key `\n`. Yes, got 1 of 1
2. what should I put in replace to replace it as new line

### Versions

1.24.1 x64

**Comment by ozbillwang** [comment]
I fixed it by myself.

enable regex in atom . (the `.*` icon)

```
find: \\n
replace: \n
```

**Comment by ajostergaard** [comment]
@rsese this isn't really a question though... It's actually at a minimum a UI or documentation bug.

It was very far from intuitive that you can only replace strings you find with a real new line when regex is enabled. If you, for example, try to replace , with \n without regex enabled you just got lots of \n strings instead of the commas. You have to enable regex for Atom to recognise the \n as a new line.
