### ISSUE TITLE
Find and replace to keep same sequence number

### ISSUE THREAD

**Issue by danez85** [atom/find-and-replace#1016]
Im looking for a way to replace a location path on multiple files that have different sequence number.

Example
Z:/user/folder1/folder2/folder3/file_01.png
Z:/user/folder1/folder2/folder3/file_02.png

When I use regex mode to look for the files I type in the find space:

Z:/user/folder1/folder2/folder3/file_*.*.png

And it finds all the files I need to replace. However, the replace result is not what Im looking for.

Here is what in type in replace space:

Z:/user/folderA/folderB/folderC/file_*.*.png

and instead of getting
Z:/user/folderA/folderB/folderC/file_01.png
Z:/user/folderA/folderB/folderC/file_02.png

I get

Z:/user/folderA/folderB/folderC/file_*.*.png

How can I replace to keep the same sequence number so that the result I get is:
Z:/user/folderA/folderB/folderC/file_01.png
Z:/user/folderA/folderB/folderC/file_02.png

Thanks

**Comment by rsese** [comment]
Thanks for reaching out!  Please use the resources mentioned below if you have questions or need support.  

I'm definitely not a regex expert but after reading a bit through http://www.regular-expressions.info/ and using https://regex101.com, this seems to work?

Find `Z:\/user\/folder1\/folder2\/folder3\/file_(..)\.png` and replace with `Z:/user/folderA/folder2/folder3/file_$1.png`.

If that doesn't work or you still have trouble, please reach out on the Atom Slack or the message board.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
