### ISSUE TITLE
Unable to edit text in search field after toggling search

### ISSUE THREAD

**Issue by john-cj** [atom/find-and-replace#1067]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sometimes you will not be able to edit text in search field.

### Steps to Reproduce

1. Create new tab with 2 lines: `foo` and `bar`.
2. Press Ctrl-F. Type "foo" in search field in bottom pane. Then press Escape to close the pane.
3. Press Ctrl-F again. Press End or Right-Arrow keys on the keyboard - it will not do anything. The cursor will be just blinking in the very start of search field.

### Versions

Atom 1.34.0 ia32. Windows 7.

**Comment by rsese** [comment]
Thanks for opening the issue in this repository :+1:

I'm positive there's an issue very similar to this but was having trouble with search - we'll close if we find it later but confirmed for now with 1.34.0 on macOS 10.12.6.

**Comment by daviwil** [comment]
Confirmed on `master` too.  Seems the key here is to *not* press enter in the search field, causing the first result to be selected in the editor.  When text is selected in the editor, the search field is focused and selected correctly.  Otherwise, the cursor goes to the front of the search field and *seems* like it's stuck but it actually moves as expected if you arrow right a couple times and type a letter.
