### ISSUE TITLE
Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided dou...

### ISSUE THREAD

**Issue by hexfs** [atom/find-and-replace#1073]
1. Clone a big project in github.
2. Start replacing space) with ) without stopping and doing Ctrl + Enter.

**Atom**: 1.34.0 x64
**Electron**: 3.1.3
**OS**: linux 4.20.10-zen1-1-zen
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.215.14

### Stack Trace

Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.

```
At /usr/lib/atom/node_modules/find-and-replace/lib/project-find-view.js:268

TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.
    at subscriptions.add.model.onDidReplacePath.result (/usr/lib/atom/node_modules/find-and-replace/lib/project-find-view.js:268:43)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at atom.workspace.replace (/usr/lib/atom/node_modules/find-and-replace/lib/project/results-model.js:221:22)
    at /usr/lib/atom/src/task.js:120:25
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at ChildProcess.<anonymous> (/usr/lib/atom/src/task.js:72:34)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
  2x -6:53.6.0 core:backspace (input.hidden-input)
     -6:52.7.0 core:move-down (input.hidden-input)
  3x -6:52.4.0 core:backspace (input.hidden-input)
     -6:51.2.0 core:move-down (input.hidden-input)
  2x -6:50.9.0 core:backspace (input.hidden-input)
     -6:49.2.0 core:move-down (input.hidden-input)
  3x -6:49 core:backspace (input.hidden-input)
     -6:14.6.0 core:select-all (input.hidden-input)
  2x -6:14.3.0 core:backspace (input.hidden-input)
     -6:12.6.0 core:confirm (input.hidden-input)
  2x -6:11.4.0 core:backspace (input.hidden-input)
     -5:51.9.0 project-find:show-in-current-directory (div.header.list-item)
     -5:50.3.0 core:confirm (input.hidden-input)
     -4:01.3.0 project-find:confirm (button.btn)
     -3:06.2.0 project-find:show-in-current-directory (div.header.list-item)
  4x -3:05.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!

> **Atom**: 1.34.0 x64
> **Electron**: 3.1.3

Based on these versions, we've determined that you are currently using an unofficial build or distribution of Atom (the official stable 1.34.0 release ships with Electron 2.0.16). Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
