### ISSUE TITLE
Search temporary unsaved files

### ISSUE THREAD

**Issue by jefferyyuan** [atom/find-and-replace#1081]
- Usually we have multiple temp files(maybe some logs, exception etc, we don't want to save them), later we would like to search against these tmp files.

- Atom stores tmp files in IndexDB, and seems we can do full text search in IndexDB.
Thanks.

**Comment by rsese** [comment]
Thanks for contributing!

I assume this means you'd basically like to search in your open tabs since the files aren't saved?  In that case, I think this request is pretty close to https://github.com/atom/find-and-replace/issues/241 so we'll close in favor of that issue.

Additionally, please use the issue template when opening issues - if any part doesn't apply, feel free to just say something like "not applicable".   The template information and format is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
