### ISSUE TITLE
Solus Linux can't index/find in all files

### ISSUE THREAD

**Issue by framerate** [atom/find-and-replace#1103]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Find in all files doesn't work in Solus Linux

### Steps to Reproduce

1. Open Atom
2. Open a project
3. Find in all files and watch "Indexing" never stop

![image](https://user-images.githubusercontent.com/74291/66261421-c0071d80-e781-11e9-8d2a-21ab15e988d5.png)

**Expected behavior:**

Should find in all files

**Actual behavior:**

Indexes forever

**Reproduces how often:**

100%

### Versions

Latest on Solus Linux

### Additional Information

There was a previous problem with the fuzzy finder, which Solus devs were able to fix for me. here is the response from that:

> Looked into it, seems they were trying to force their git-utils to use a specific version of libgit2, with a specific ABI. Good stuff. Seeing about fixing it.

Might be related!

**Comment by Arcanemagus** [comment]
> Latest on Solus Linux
> files/0001-Revert-git-utils-to-5.5.0-to-fix-undefined-symbols-o.patch

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by framerate** [comment]
@Arcanemagus Just to be clear I understand, the only way for me to use Atom on Solus Linux is:

- To use their unofficial port (which is broken and you don't recommend)
- To build from source? (it's not debian/etc based)

Do you offer a snap or appimage as an alternative?

**Comment by Arcanemagus** [comment]
If Solus doesn't support one of the common package formats that appears to be your options.

> Do you offer a snap or appimage as an alternative?

Unfortunately no, as far as I know there are only RPM and Debian packages.

----

Interestingly from [that commit message](https://dev.getsol.us/R394:2dc2803ba63f573b898486efd92a4eafbea56b49) it seems that the Solus devs think there is something wrong with the way `git-utils` is currently packaged, as it's working everywhere else this sounds... _odd_, but it's certainly possible. If they think there is something that could be fixed there it would be great if they could file an issue or open a PR fixing it. (I personally don't know enough about that package to say either way.)

**Comment by framerate** [comment]
Yeah I'm stuck in the middle. I'm a long-time Atom supporter (since day 1) and I'm also a long time Solus supporter.

But now I'm running Ubuntu-Budgie for development and VS Code on my Solus machines :/

I'd like to help Atom (and Solus) but I don't know where to start since I'm not familiar with contributing to Linux (or if the bug would be on Atom!) So i'm hoping someone will point me in the right direction soon.

**Comment by Jacalz** [comment]
Hello. I am the Atom maintainer in Solus and I just want to chime in on the matter and say that we do not modify the project much. The only thing we do is pull down the files, build them and install them with a little patch to fix the other issue mentioned above. I have double checked and that patch does not cause this issue.

Have a look at the build file [here](https://dev.getsol.us/source/atom/browse/master/package.yml) for more information.

But on the subject on the issue at play here, I have been looking deeper in to the problem. I can indeed replicate it with the version of atom for 1.40.0 and 1.40.1 and the 1.40.1 version with the git fix. Version 1.39.0 of atom does however not seem to have the issue. That means that something broke inside atom most certainly, if I am understandings things correctly. Pretty much nothing on the packaging side changed between [1.39.0 and 1.40.0](https://dev.getsol.us/R394:43619d8ab962d0b267fe588ded91e8bf3999e4a5). I am currently building the 1.41.0-beta1 version to see if that issue is persistent in that version too.

I have checked through outputs to the console and I did not find any related errors so if the new version doesn't fix this, I really don't know what to do then.

Until this is fixed, if you want to use Solus, the Flatpak works absolutely fine as a little tip :)

**Comment by framerate** [comment]
Thanks @jacalz!

Maybe @Arcanemagus can shine some light on it and I can help?

**Comment by framerate** [comment]
Without meaning any disrespect, I wanted to update this thread with my thoughts for the next people who find it.

I was the last person at my office to use Atom. I've been using it since the beta and I have A LOT of love for it and everyone who puts in hard work to make it work. But it's been having a lot of small problems that add up. Many of the plugins I use (Namely the React one) are in maintenance mode at best. When my theme broke the author made it clear he didn't use it anymore but was still willing to fix it for me (and someone on the Atom team (https://github.com/atom/github/issues/1911). Thank you so much @annthurium and @rsese for helping with that one! 

But this time I hit a problem where Atom didn't work with my OS which slowed down my work on my company and my day job and I wasn't sure how to proceed. 

I understand why you don't want to support all favors of Linux. That shit is nuts. And as @Jacalz mentioned, the Flatpak DID install (but the internal git tools were all broken). So I was stuck with an editor and workflow that didn't work on my operating system and two companies relying on me to get programming done. So I finally made the switch to VSCode. I know it's stupid but it's kind of an emotional switch for me as I've been an evangelist of Atom since day 0.... and one of the last holdouts from my programming friends. I'm not sure what could be done differently, though. Maybe officially support the Flatpak? At the very least maybe offer more assistance here since myself and the package maintainer showed a desire to help fix it, but this is OSS and I know you guys are bombarded with bullshit like this that isn't part of your core focus.

If you work on Atom, please take this as constructive feedback. I love you guys (and you gave the world Electron which my whole company is based on! <3 <3 <3). 

If you're having trouble on Solus with Atom and you find this thread, try this: https://github.com/microsoft/vscode-atom-keybindings

<3

**Comment by Jacalz** [comment]
@framerate I now have a new package version up for review that should fix all of your issues mentioned here and a few more. File indexing is now working like expected: https://dev.getsol.us/D7867

I ultimately switched from building from source and use the prebuilt tarballs. This lets us avoid the long build times, issues with building using NODE12 and other stupid little issues that shouldn't be happening. I am so tired of electron apps in general...

**Comment by framerate** [comment]
Awesome. I can try and test it for you at least! Sadly I finally made the
switch to vscode due to this issue thread. Can't have an editor that
doesn't work with my OS, you know? But I still have Atom installed and will
let you know!

**Comment by Jacalz** [comment]
Thanks. I must Samir that I switched to vscode too, but for totally different reasons. Will continue maintaining atom on Solus though...
