### ISSUE TITLE
There's no default shortcut for replace-next in windows

### ISSUE THREAD

**Issue by Unentokku** [atom/find-and-replace#1104]
In keymaps/find-and-replace.cson there isn't a win32 shortcut for replace next like there is for [darwin](https://github.com/atom/find-and-replace/blob/5423707b26d3d8066569c3a63671e67f6c134840/keymaps/find-and-replace.cson#L17). Perhaps it was removed because the cmd-alt-e used for darwin normally makes the € sign.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

See the discussion here for more context about `replace-next` and a default Windows keybinding: https://github.com/atom/find-and-replace/pull/713#issuecomment-270999759.  And you can add your own [keybinding](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings) if you'd like of course.
