### ISSUE TITLE
Find and replace with preserve case

### ISSUE THREAD

**Issue by jasonkim** [atom/find-and-replace#165]
When you search for abc (case insensitive) and want to replace it with xyz, it should match on Abc and replace it with Xyz. This is a feature that I found useful in sublime.

**Comment by claaslange** [comment]
:+1: for the simple case as well

**Comment by orospakr** [comment]
Emacs also has this behaviour, by default, and it's profoundly useful.

**Comment by littlebee** [comment]
+1 very useful  intelliJ feature.  I miss.    Here is the use case, it is not, imnsho, an "edge" case considering we frequently, for multiple languages, mix the case to indicate something is a class or a var.  I want to replace 'collection' below with 'model' without doing 2 f&r:

```coffeescript
  ###
    Collection component provides a collection context to all children
  ###
  class x.Collection extends React.Component
    displayName: "widgets.react.Collection"

    @propTypes:
      collection: React.PropTypes.oneOfType([
        React.PropTypes.instanceOf(Backbone.Collection)
        React.PropTypes.func
      ]).isRequired
      fetch: React.PropTypes.bool
      fetchOptions: React.PropTypes.object
```

**Comment by Rosseyn** [comment]
Hands down most awaited feature.

**Comment by BigWillie** [comment]
+ 1 - this would be killer to have!

**Comment by keomaborges** [comment]
+1 - I still have to open Sublime to do this kind of replace.

**Comment by adambuczynski** [comment]
This issue was opened almost 2 years ago, it would be great to have it implemented.

I too would find it very useful, since in my Angular projects I often need to duplicate existing modules and then rename their name to something else. This affects not only the module name, but also the controller name, template name, etc. And these could all be in different cases, for example camelCase, PascalCase, or just simply lowercase. Currently, this would require me three find & replace operations.

If there'd be a toggle to trigger case-aware replacement, that would save a lot of time.

Bonus points if support for snake_case or kebab-case (dasherized) strings can also be added. This would probably involve detection of what case the search term and replacement term are in (and I think both should match). Then, if doing a find & replace with the toggle turned on, all other case variants could be generated from the search term and found & replaced by the equivalently cased replacement term.

**Comment by ronnyroeller** [comment]
+1 for the simple case

**Comment by siliconjohn** [comment]
+1 - I still have to open Sublime to do this kind of replace.

**Comment by mliq** [comment]
+1

**Comment by diddierh** [comment]
+1 I still have to use subl for this simple task

**Comment by hillam** [comment]
+1

**Comment by adamjking3** [comment]
+1

**Comment by friedmud** [comment]
👍

**Comment by bostrom** [comment]
An Atom port of Sublime's [MultiEditUtils](https://github.com/philippotto/Sublime-MultiEditUtils/issues/23) would be awesome!

**Comment by rromanw** [comment]
+1

**Comment by itlamb** [comment]
Place try my new package https://atom.io/packages/case-keep-replace ;)

**Comment by adambuczynski** [comment]
@itlamb Didn't work for me unfortunately. First test I tried was to replace `amountowing` to `amountneeded` with your package, but it didn't make replacements in this code:

```js
$scope.amountOwing = user.getMoneyOwing();
```

After pressing replace button it just wouldn't do anything. No message, no result, no replacements :(

**Comment by itlamb** [comment]
Hey @adambuczynski, could you check if there is any massage in Developer Tools / Console?

**Comment by itlamb** [comment]
But if you enter `amountowing`string it will not be found - it doesn't work that way. You should enter `amountOwing` and `amountNeeded` and the package will look for `amountOwing`, `AmountOwing`, `AMOUNTOWING` and replace them by `amountNeeded`, `AmountNeeded` and `AMOUNTNEEDED`.

**Comment by adambuczynski** [comment]
@itlamb ah right sorry, my example didn't make sense.

**Comment by adambuczynski** [comment]
It would be nice there'd also be a way to handle dashes and underscores properly, e.g. snake case and dasherized strings.

This is because usually when refactoring code one would need to refactor several different common formats of essentially the same string, e.g.:

- `someString`
- `SomeString`
- `some-string`
- `SOME_STRING`

**Comment by itlamb** [comment]
Yes, this is very good idea - thank you @adambuczynski :)

**Comment by Ben3eeE** [comment]
@itlamb @adambuczynski Can you please move the conversation about another package to that packages repository. Thanks.

**Comment by adambuczynski** [comment]
@Ben3eeE my last comment was specific to this issue, sorry if this wasn't clear.

**Comment by exdeniz** [comment]
+1

**Comment by henhal** [comment]
+1

**Comment by marcelovsantos** [comment]
+1

**Comment by RingOfStorms** [comment]
+1

**Comment by okonomiyaki3000** [comment]
:+1:

**Comment by bitstrider** [comment]
+1 can't wait for this to hit release, def a game changer for renaming

**Comment by RustyDev** [comment]
+1

**Comment by parkan** [comment]
+1

**Comment by lee-dohm** [comment]
Thanks for everyone's help and suggestions. Unfortunately, upon further review this isn't something that we want to maintain long-term. We do think that it would be very useful as a community package however.

Thanks again for everyone's input.

**Comment by jagadeesh52423** [comment]
I would like to give my suggestion here. Whenever user tries to replace a word, then we just need to find whether all are in same case or different. If not different, then we can replace normally. else we can show them suggestions as set
[lets say user is trying to find "foo" and replacing with "bar"]
foo -> bar
Foo -> Bar
fOo -> bar [this is difficult if we lengths are different, so we will show them normal option]
These foo's are set of different cases in user's search.
user will chose and replace accordingly.
Ping me at jagadeesh52423@gmail.com if you need more clear picture.

**Comment by hmrm** [comment]
@lee-dohm is there a link available to aforementioned review?
