### ISSUE TITLE
Add "Find Next in Project"

### ISSUE THREAD

**Issue by malmckay** [atom/find-and-replace#200]
After I "Find in Project", I would like a "Find Next in Project" keybinding, to jump to the next file that has a match. 

It's useful when I am doing a find and replace, but don't want to replace every occurrences

**Comment by consti** [comment]
Any progress on this? Thanks! :)

**Comment by duanefields** [comment]
yea, not sure why Find Next doesn't honor the "In Project" context

**Comment by thomasthorsen** [comment]
Please keep it separate from the regular find-next/previous (f3/ctrl-f3) within a file so that I can do a project wide search and go through all the project wide results one by one while still being able to search for other things within the individual files (using ctrl-f). In Sublime Text the project wide find-next and find-previous is on f4 and ctrl-f4 respectively, while the find-next/find-previous is on f3 and ctrl-f3 as in Atom.

**Comment by benogle** [comment]
Closing this in favor of #460 as it has a little more information.
