### ISSUE TITLE
Searching within current selection is very buggy

### ISSUE THREAD

**Issue by 50Wliu** [atom/find-and-replace#298]
**Scenario 1**: Let's say I want to find a phrase in a certain selection of code.  To do this, I would:
1. Select that area of code (lines 17-32)
2. Press <kbd>Ctrl</kbd>+<kbd>F</kbd>
3. Search for that phrase (`include`)
4. Press `"Only in Selection"`

*Expected result*: FnR would search in that selection and maintain the selected code
*Actual result*: It does search only in that selection but also un-highlights the selection in order to select the first match as soon as I press `"Only in Selection"`
![Atom](https://cloud.githubusercontent.com/assets/2766036/4586154/e7e5cf7a-5011-11e4-8c6b-ecb1b045d065.png)

**Scenario 2**:
1. Have FnR already set to `"Only in Selection"`
2. Select that area of code (lines 17-32)
3. Press <kbd>Ctrl</kbd>+<kbd>F</kbd>
4. Search for that phrase (`include`)

*Expected result*: FnR would display the proper number of results
*Actual result*: FnR displays `No results found`
![Atom](https://cloud.githubusercontent.com/assets/2766036/4586199/aff97020-5012-11e4-8ff6-a29640a2ab15.png)

**Scenario 3**:
1. Search for any phrase in FnR without selecting Only in Selection
2. Press Only in Selection (should display No results found)
3. Unselect Only in Selection
4. Notice how the first line that matches your phrase gets selected (actual number of results displayed)
5. Select and unselect Only in Selection
6. Notice how the second line that matches your phrase gets selected
7. Keep selecting and unselecting Only in Selection

Version 0.136.0, safe mode, Windows 7 x64.

**Comment by wyand** [comment]
I think the selection should not be modified when within-selection is enabled (including when within-selection is toggled). In safe mode, this seems to be the cause of other bugs, and also has a very poor user experience:

![within-current-selection](https://cloud.githubusercontent.com/assets/1288857/6528737/1c972cce-c3f2-11e4-9918-f03e9aaa5bff.gif)

Note that when "within current selection" is toggled on, the selection in the editor is modified to select the first match, even though no actual searching operation has been performed. On the subsequent "replace all," the matches in the original selection are all modified.

As a design concern, a find and replace that has "within current selection" support should never modify the selection; it is a piece of input to the find and replace, and modifying the selection makes the find and replace workflow stateful and dependent on the order of operations.

Consider the following:

1. A user selects the top half of a large document.
2. A user enters a find pattern that matches a large, multi-line segment of text.
3. The user toggles on "within current selection." At this point, the selection is modified to be the first match, and all matches are marked with outlines.
4. The phone rings. User returns an hour later.
5. The user returns to find:
    * A selected and highlighted match for the pattern, visible on screen
    * A second, highlighted, unselected match for the pattern, not visible because it is below the bottom of the editor
    *  A third, unhighlighted, unselected segment of text that would match the pattern; but did not, because it was not within the original (now lost) selection
6. The user executes "replace all." The visual cues to the user (entire selection visible, within selection enabled) indicate that one replacement will be made. Two replacements will be made.

Of notable weirdness is that, if "within current selection" was _already enabled_ when the user opened the search and replace tab, the interaction would be different. The selection visible in the editor when "replace all" is executed is the _original_ selection, not the first match.

It is perhaps a bit contrived -- but it should not be possible to get confusing results from a simple operation like find-and-replace-in-selection. This is a core, simple, should-just-work thing.

I think the key to this is removing find-and-replaces ability to modify the selection. The selection is valuable user data -- someone has made the selection, and is likely to want to work with it for more than the current operation (or for that matter, may want to work with it through the end of a single operation).

While this may seem a heavy change, it also solves another issue -- many packages shift focus to the editor when the selection changes. Outside of safe mode with almost any grammar except plain text enabled, toggling "within current selection" doesn't just kill the selection, it puts focus on the editor. While this could (and perhaps should) be filed as a bug against the packages in question, it does add some extra support for disabling the selection modification.

**Comment by SpainTrain** [comment]
:+1: These are getting pretty aggravatings

<small>Regarding +1 spam: https://www.change.org/p/github-inc-add-voting-functionality-for-github-issues </small>

**Comment by benogle** [comment]
_From @AgentME on #534_

There might be a few issues in this, or there's something fundamental about how it works that I missed. I'm just going to write out my most recent experience after verifying it's reproducible.

1. Push cmd+f, turn off all of the regex, case sensitivity, within selection, whole word options, push escape to close it.
1. Open a pre-existing file.
2. Make a selection. Let's say it's over the word "function".
3. Push cmd+f.
4. Set the "Find in current buffer" field to "[a-z]", set "replace" field to "a", turn on regex mode and within current selection.
5. Somehow the only thing found is the 'u' in the originally selected word "function".
6. Push escape to close the finder.
7. Make a new selection. I've picked the word "var".
8. Push cmd+f.
9. Change the "Find in current buffer" field back to "[a-z]".
10. Push find. Things seem to work fine. Each individual letter of "var" is matched. Pushing "replace all" makes it into "aaa".
11. Push escape.
12. Make a new selection. Make a second disjoint selection simultaenously by selecting something else while holding command. (Take a few minutes to make many more selections over the file to get the whole experience if you wish.)
13. Push cmd+f. If your last selection spans multiple lines, then you will find that the "aaa" which used to be "var" will be what the finder considers to be your selection even if it's not part of your current selection, and all of the highlights you just spent time doing will be disregarded. Otherwise, only your last selection will be considered by the finder, even though all of your highlights are still visible until you hit find.

**Comment by rivo** [comment]
To add to this, when I repeat a previous search on a new selection (i.e. I don't enter a search term again), the new selection is not searched but instead the old selection is. Here's an example:

![far](https://cloud.githubusercontent.com/assets/480930/10998706/54518360-8497-11e5-8e24-6a00374b946f.gif)

We're in v1.1 and this item has been open for more than a year. What needs to be done to get this fixed?

**Comment by benogle** [comment]
> What needs to be done to get this fixed?

It needs someone to dedicate time to thinking about exactly what the behaviors should be, then have someone to write the code. Unfortunately, at this time it is very low priority for the core team. If someone is interested in taking this on, I can help guide them.

**Comment by 50Wliu** [comment]
Closing this since #598 has been merged.  If there's still issues I'll create new ones.
