### ISSUE TITLE
Unexpected search results from "Search in directory"

### ISSUE THREAD

**Issue by jugglingnutcase** [atom/find-and-replace#309]
i've been hitting an issue that i'm having trouble pinning down to a certain section of source code, so i'll  put it here. i'm sorry if this isn't the right package! i couldn't really find a similar issue in the other packages.

i hope i'm not taking crazy :pill:s!

## my problem

When using "Search in Directory" in Windows, sometimes i get no results when i expect the search to find something.

i've only seemed to be able to reliably reproduce this behavior in directories with `.`s in them, like often seen in .NET projects, and that's what i used to reproduce the issue.

## example of my issue

In the following i'm running Atom in safe mode:

![bug-report](https://cloud.githubusercontent.com/assets/238079/5052301/4be45ec6-6c0d-11e4-938c-22a3df4524cf.gif)

## Steps to reproduce

On a Windows machine

* Clone/download the source for the [Nancy project](https://github.com/nancyfx/nancy/) and open it in Atom
* Start a "Find in project" and search for `Nancy.Cryptography`
  * The find returns results, which seems to work as expected
* Open up tree-view and right click `src\Nancy.Authentication.Forms.Tests` and select "Search in Directory"
* Search for `Nancy.Cryptography` again
  * No results are found, *i expected that there would be results here* because that folder had results in the aforementioned search.

What's interesting is that if i click on the "FormsAuthenticationConfigurationFixture.cs" file in tree-view, suddenly a result appears! i wouldn't expect it to find one then, earlier it returned nothing. After closing that file, searching again returns no results.

## other information

i don't see any errors or traces in the console.

## Versions

* **Atom:**       0.146.0
* **Atom-Shell:** 0.19.1
* **OS:**         Microsoft Windows 8.1 Pro
* **Misc**
  * apm 0.111.0
  * npm 1.4.4
  * node 0.10.33
  * python 2.7.8
  * git 1.9.4.msysgit.1
  * visual studio 2013

**Comment by izuzak** [comment]
Just a note: I was able to reproduce this in the latest Atom (0.179.0) on OSX.

**Comment by clafollett** [comment]
Any idea when this will get replaced or if there is a work around? We are switching from Visual Studio and C# development on Windows to Go using Atom on Mac OS X. I find myself doing a lot of directory searches to understand the new code base but this bug is making this very difficult.

Thanks!

**Comment by benogle** [comment]
@clafollett is the issue limited to directories with dots in them as well?

**Comment by ryush00** [comment]
I also happens.

**Comment by clafollett** [comment]
@benogle sorry for my delay in responding. Yes I believe the issue is limited to directories with embedded ".".

We develop in Go. Using the command "go get github.com/repo-name-here" causes Go to create the following directory structure given a $GOPATH of "/dev/go/": /dev/go/src/github.com/repo-name-here/

If my root Atom project path is "/dev/go/src" folder - which is preferred - then only searches which are for file extensions work. Example: *.go. If I limit the path search to just a folder name such as "repo-name-here", I do not get results back.

On the other hand, if my project path is narrowed to just "/dev/go/src/github.com/repo-name-here", I can use folder name filters to limit searches.

We also use the Go "vendoring" concept of embedding 3rd party github.com repos directly in our projects "vendor" folder such as: "/dev/go/src/github.com/reponamehere/vendor/github.com/<3rd party paths here>". Searches in those directories do not work.

As you can see, its not easy for us to remove the "." in all our paths and depending on what the root project path is, it may make negate any folder name filtering.

There are some work arounds which is to narrow the scope of the root project but it would sure be nice to not have this limitation.

**Comment by clafollett** [comment]
Please note, I'm using Atom 0.210.0 on OS X Yosemite 10.10.3

**Comment by toqueteos** [comment]
Not just Win32, same on OSX 10.10.4 with Atom 1.0.2. No `.` involved in the search.

**Comment by jugglingnutcase** [comment]
Fair point... i'll update the title.

**Comment by flemay** [comment]
Same here using atom 1.0.3! To solve the problem I need to put "*" at the end of File/directory pattern box. For instance: `github.com/paypal/gatt/*`

**Comment by ramen-drama** [comment]
Didn't think it was dot in directory for me, because I only noticed it when I had multiple projects in one window. Finally noticed the parent project directory is added when you search in directory with multiple projects open, and of course my projects include .com in their naming. Update to 1.0.5 fixed this for me. Hoozah!

**Comment by ohgodspidersno** [comment]
Any fix to this yet?
