### ISSUE TITLE
Where is "Find prev"?

### ISSUE THREAD

**Issue by alexandernst** [atom/find-and-replace#322]
Somewhere between .151 and .153 the "Find prev" button (when opening Find&Replace with Ctrl+F)  disappeared. Is this a bug? 
If this was a decision that was made, can you reconsider it? I can't recall any "Find" utility in any editor/web browser/whatever not having a "Find prev" button near the "Find next" button.
It's really not comfortable having to go to the top menu, then clicking "Find" and then clicking "Find prev" in the menu.

**Comment by ricardograca** [comment]
For those of us not using a Mac what's the keyboard shortcut for Find Previous? I tried Ctrl+Shif+g but that only opens the Styleguide.

**Comment by 50Wliu** [comment]
`Ctrl+Shift+F`

**Comment by ricardograca** [comment]
Nope, that's find in project.

**Comment by benogle** [comment]
@ricardograca that's probably a bug in styleguide. Can you open an issue on styleguide? Can you open the keybinding resolver (`ctrl-.`), use the key command and screenshot it for the new issue?

**Comment by 50Wliu** [comment]
You could also do `Shift+Enter` while the cursor is in the find box (sorry about the wrong shortcut listed above).

**Comment by ricardograca** [comment]
@benogle How can a keyboard shortcut conflict between two packages be a bug in one of them? If I open a bug over there I'm pretty sure they will say it's working as intended and it's this package that needs to change the shortcut. Even so I'll open the issue over there to see what they say.

All of this could easily be solved by having a proper "Previous" button ;)

@50Wliu Nope, that does nothing.

**Comment by benogle** [comment]
I maintain both of them. It was an oversight on my part.

**Comment by 50Wliu** [comment]
Huh, I swear shift+enter works for me.  Odd.

**Comment by ricardograca** [comment]
Keybinding resolver shows that should indeed work, as it is reporting the correct action: `find-and-replace: show-previous`, however there is a grey X next to it. Not sure what that means.

**Comment by benogle** [comment]
`shift-enter` should only work when in the find box, not a regular editor.

**Comment by ricardograca** [comment]
Funny. It wasn't working a moment ago, but after I clicked the find box it now works properly all the time. Go figure... Thanks for all your help.

**Comment by davidbarratt** [comment]
@benogle
It would be nice for the few of us (me) that do use that button frequently to at least have the option of having it (i.e. in the settings somewhere)

**Comment by alexandernst** [comment]
Indeed, it's a requested feature, why not let the user decide if enable it or not?

**Comment by ricardograca** [comment]
@benogle @50Wliu I now understand my confusion about `Enter` and `Shift-Enter` not cycling through next/previous matches. That keyboard shortcut only works when looking in the current file. When in *Find in Project* mode it doesn't work, so there doesn't seem to be a way to cycle through the results when in that mode.

Man, the issues that a couple of simple Next/Prev buttons would solve... :)

**Comment by MrBlack13** [comment]
Does this not work with F3 (find next) and SHIFT-F3 (find previous)?  It seems to be working for me.

**Comment by polarathene** [comment]
Those shortcut keys work. They weren't apparent to me though, I prefer to have a prev button. I'd like to see the previous button as an option in settings that I can switch on if you feel it shouldn't be visible by default.

**Comment by ricardograca** [comment]
See #453.

**Comment by ricking06** [comment]
can anyone add find prev button beside find. like make find button shorter and add the find prev button.

**Comment by jonathan-dejong** [comment]
Just browsed through the code and thought I'd mention that you can also hold shift while pressing "Find" to traverse upwards.

**Comment by JackWells** [comment]
Anyone who codes and needs to find the last declaration needs this button all the time - when one's hand is already on the mouse for other things.  Tired of going up to the menu - started cussing today from this (again), and decided to risk and upgrade, because the find-replace-with-prev wouldn't work with my older version.  Well, sure enough, I now have a broken Atom editor (nothing opens).  

I like the look of the really old versions and haven't experienced any improvements from any upgrades for years, so would like to go back to v.151, where the GUI was much better (had find-all, button too - also helpful and now gone).  But on the git, I don't see versions that old listed.  Where to find it?

**Comment by maxprkr** [comment]
Statistics also shows that the 'Quit' is used seldom. At most once per session....

**Comment by GCDeveloper** [comment]
This left me bamboozled for a bit, but holding <shift> when clicking the find button is the solution to find previous.

**Comment by fseminario** [comment]
@benogle Can we pause for a moment and acknowledge that low interaction doesn't equate to omission? e.g. if I'm shopping online and I decide to cancel my order, because I'm the minority of users should I not be able to cancel my order? That logic is fallible. Your not alone though as its a common justification. I here it all the time at work - sometimes its correct for the user and sometimes it is not. Context has to be considered. In this case you removed an interaction that is not used often but equally as important as the next button. 

Disappointed that this is considered acceptable from the atom team.

Thanks @50Wliu for sharing the implicit workaround.

**Comment by rsese** [comment]
Thanks everyone for the feedback.  I double checked with the team and confirmed that this still isn't something that will be added so we're going to lock the issue for now.  Thanks again to @50Wliu and @GCDeveloper for sharing a workaround.
