### ISSUE TITLE
Please add search as you type just like Eclipse STS

### ISSUE THREAD

**Issue by izuzak** [atom/find-and-replace#329]
_From @andreicristianpetcu on December 14, 2014 23:59_

Hi, 

Please add search as you type just like Eclipse STS http://youtu.be/1lH7Zla5ubQ

Thank you for building Atom! :D

_Copied from original issue: atom/atom#4613_

**Comment by rbu** [comment]
I have never worked with Eclipse STS, but I second the request for search as you type.

In my understanding it is already querying the editor view for search strings as you type, but currently the cursor does not automatically jump. You have to hit Enter to jump in the text.

**Comment by andreicristianpetcu** [comment]
@rbu  Not only that, but it searches ALL the files in the workspace in the same time. Please check the video http://youtu.be/1lH7Zla5ubQ I also have this feature in Vim with :CtrlPLine from kien/ctrlp.vim.

**Comment by benogle** [comment]
Searching as you type already exists, and there is now an option to move to the first result as you type. Closing this out.

**Comment by jancborchardt** [comment]
@benogle is the option on by default? If not would be good, since most people do not fiddle with settings too much.

**Comment by benogle** [comment]
No, it's off by default at this time. But it could potentially be the default in the future. We're careful about changing defaults so as not to surprise a bunch of people.

**Comment by paulklemm** [comment]
@benogle: I cannot find this option in the settings. Can you please tell me where it is located?

**Comment by torarnv** [comment]
@benogle I'm with @paulklemm, I can't find an option that toggles moving to the first result as I type my search after pressing Cmd+F on OSX. The results are live highlighted, but I still have to press enter to move the cursor to the first result.

**Comment by benogle** [comment]
It's this one: 

![screen shot 2015-10-02 at 10 49 44 am](https://cloud.githubusercontent.com/assets/69169/10253649/503fc062-68f3-11e5-9da1-38153a96baba.png)

**Comment by paulklemm** [comment]
@benogle, @torarnv Ah, thanks, found it! It is part of the find-and-replace atom package. Found it using this tweet: https://twitter.com/tschaub/status/638432913537679360.

**Comment by andreicristianpetcu** [comment]
Hello, 
Either I don't know how to use this feature, or it was not implemented as I asked. Please check out how IntelliJ implemented it here: https://www.jetbrains.com/idea/nextversion/img/15/15_find_preview.gif The whole point of the feature I requested is to filter lines from all the files in the entire project. Check out how I do this in Vim: I first search for "@ Captor" the I search for "RunWith" and then for something in comments "Holds all the requests" https://youtu.be/j_p4VULH3cY You can also take a look at the initial video I posted with Eclipse.

If you cannot implement it because it is complicate, it's ok, if you don't have time to work on it again I understand. The feature that was implemented is a great, but it is not what I searched for.

Thank you for all your effort in building Atom :)

**Comment by nicooprat** [comment]
Here, the last one at the bottom:

<img width="915" alt="capture d ecran 2016-09-14 a 18 05 01" src="https://cloud.githubusercontent.com/assets/645641/18519883/cf12fa20-7aa5-11e6-8f47-1bbdfea9f3dd.png">
