### ISSUE TITLE
The border of the selected result is missing

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/find-and-replace#406]
Only if I previously selected something then the current find result has border, otherwise there will be mistakenly no border. I don't mean the borders of all results, but just the border of the current result. For example in "One Light" theme the borders of all results are black and the border of selected result should be blue.

**Comment by izuzak** [comment]
@zhanzhenzhen I'm not sure I'm following. 

Could you provide exact steps to reproduce the problem in a specific them, and clearly explain what you observed and what you expected to observe instead? Screenshots would be helpful as well.

**Comment by zhanzhenzhen** [comment]
OK. Sometimes it's like:
![bug1](https://cloud.githubusercontent.com/assets/731796/8057202/c723ef6c-0ee1-11e5-89ec-771eedd4e265.png)
Sometimes (if already something is selected before pressing command+F) it's like:
![bug2](https://cloud.githubusercontent.com/assets/731796/8057205/cd25d8da-0ee1-11e5-9806-ee8c33c4b478.png)

**Comment by benogle** [comment]
I see this too. 

* Place cursor at 0,0
* cmd-f
* type `return`
* hit enter
* no outline

```js

var millis = function() {
  var d=new Date();
  return d.getTime();
};

var compute = function() {
  return true;
};

```

**Comment by benogle** [comment]
@as-cii can you take a peek at this? I think this may have been a regression from the tiling changes

**Comment by as-cii** [comment]
Hitting return during a *find-and-replace* session causes two highlights decorations to be created:

* The *find-and-replace* highlight (which applies a border)
* The *selected text* highlight (which applies a background-color)

It seems like the highlights are being created exactly in this order, thus causing the background color to hide the border.

The most straightforward solution I could think of is putting a `z-index` on the border highlight, forcing it to appear always in front of other highlights. If we decide to go down this path, I would suggest to put this styling in the find-and-replace package, so that themes do not have to bother about this at all.

@benogle: I am a bit unsure this was a regression caused by tiling per se, as it shouldn't have impacted these aspects, but I suspect the recent changes on `box-sizing` could have altered this behavior.

**Comment by benogle** [comment]
> @benogle: I am a bit unsure this was a regression caused by tiling per se, as it shouldn't have impacted these aspects, but I suspect the recent changes on box-sizing could have altered this behavior.

You're probably right. I was making assumptions, and probably should have looked into it. Thanks for fixing. :bow:
