### ISSUE TITLE
Allow closing of search pane by x, and add search to 'view'

### ISSUE THREAD

**Issue by BramVanroy** [atom/find-and-replace#419]
At first I didn't realise how to close the search pane after calling it with CTRL+F. Then I got help [at the main branch](https://github.com/atom/atom/issues/7507). It seems like a bad idea to close a pane (that's not even the main focus inside the viewport) with a key as important as <kbd>ESC</kbd>. It seems much more logical to have a simple <kbd>x</kbd> to close the search box. Possibly accompanied by a minify button. This is how the JSLint package does it (top right).

![JSLint closing button](https://cloud.githubusercontent.com/assets/2779410/8396409/166a8736-1da4-11e5-839a-0ab635dc4063.PNG)

From left to right: sort lines (n/a for search), minimise pane, close pane. Additionally, the View menu seems a good place to allow the search pane to be toggled.

**Comment by mnquintana** [comment]
You can already toggle Find in Buffer from the app menu:

![screenshot 2015-06-28 08 49 19](https://cloud.githubusercontent.com/assets/823545/8396427/a01f47e6-1d72-11e5-8613-f019a1e6ee06.png)

There's already an open issue for adding a close button: https://github.com/atom/find-and-replace/issues/347

<kbd>Esc</kbd> is the universal "dismiss" button in Atom, so that keybinding is unlikely to go away. Its usage is already very consistent in Atom, [and it's been discussed quite a lot in the past](https://github.com/atom/find-and-replace/issues/164). A close button is still a possibility, though.
