### ISSUE TITLE
Option: Previous button visibility on ctrl-F

### ISSUE THREAD

**Issue by Justicar** [atom/find-and-replace#453]
It would be very nice to have an option that lets the user decides if the previous button is visible or not in the ctrl-F window.

I have read previous issues - all closed - relating to this situation.

In all of them, I have the feeling this request has not been taken seriously. For example, duplicated issues demanding the previous button have been closed as duplicates. But never is there any mention that it will be done in the future. What bothers me most is that the main issue (https://github.com/atom/find-and-replace/issues/322) is not even related to any development request, so all fo those request are not even duplicates.
But that is out of the point, what matters the most is the option to add the previous button.

First of all, I would like to question the assumption you had when you explained that very few people use that button. How did you realized that? How many people were asked? It simply seems like a design decision since I hardly see how you could place the previous button in the interface.

In my opinion, the previous button is standard for an IDE and removing it would cause questioning and frustration to the user.

Also, If you plan on programming this, please leave this open for tracking, otherwise It feels like you're taking this suggestion to the trash.

Thank you

**Comment by bronson** [comment]
I have to agree...  When I'm using a text editor, I pretty much never click on the Find Previous button but I certainly expect to see one.  It's a big aid in discoverability.

Using # of clicks as a reason for its removal seems strange...  By that rationale, About Atom could be removed too, no?  Are there other features receiving fewer clicks that survived the chopping block?

**Comment by git-jonathankinney** [comment]
I agree as well, I can not imagine that anyone would request it be removed, or even find that it should not be there because it takes up space.  This is the first "flaw" as I would call it I have ran into on day 2 of actual use of Atom.  If using a GUI IDE at all, I expect some basic buttons to be there, and that is one of them.  I also expect an easy way to move from using the button to using keyboard shortcuts, that is my typical learning order, basics, then move to shortcut efficiency.

**Comment by Evpok** [comment]
In addition to what has already been said, there is a 'Find previous' button in the screenshot in README. I still don't understand if the button actually exists or not.

**Comment by WesHoover** [comment]
I heavily agree that there should be at least the option to show/hide the "Find Prev" button. It can be toggle-able in the preferences if need be.

**Comment by SaintPeter** [comment]
I use "Find Previous" all the time in other editors, since I'm usually using it for navigation purposes.  I was disappointed to find that it was missing, despite being shown in the `find-and-replace` module screenshots.

**Comment by paaljoachim** [comment]
I am a new user and miss having the extra buttons in place. I opened another issue in regards to the same thing. I am hoping it will be taken care of soon....

**Comment by robsonsobral** [comment]
I was thinking why there isn't a Find Prev button and I found the issue #322 .

I prefer to have a button that I only use from time to time than to have another shortcut to conflict with something else. Also, it's harder to remember a shortcut that I don't use all the time than to move my hand away from keyboard if I need to edit the previous occurrence of a bit of code.

**Comment by redtopia** [comment]
I'm sure I use "Find Prev" fewer times than "Find", but I really want a Find Prev button because the times I need it, it's important to my work flow.

**Comment by DavidePastore** [comment]
:+1:

**Comment by robsonsobral** [comment]
Have you ever had that moment when you realize you click the Find button one more time than you should? Yeah...

**Comment by redtopia** [comment]
Or when you're searching for the declaration of a variable, which you know is defined above where it's being called!!! I do this all the time, which is why I haven't made the switch to Atom yet. I really like where Atom is going, but the lack of a Find Prev button kills it for me.

**Comment by polarathene** [comment]
Is the stance from @benogle in #322 still the case? In both these issues there are plenty of requests for optional prev button but no feedback besides adding a `enhancement` label in Jul 2015. 

Is adding this option/feature difficult? If it's a time issue, could a maintainer list steps to be done to support this so a PR can be done and merged?

**Comment by redtopia** [comment]
+1. This issue is critical for me to move to Atom. I currently use ST3 and after trying out Atom, I realized that I use the previous find button all the time. The reason is obvious.... You want to go to the declaration of a variable that you are looking at, which means you need to search backwards.

**Comment by jrpilat** [comment]
+1.  I'm interested in seeing the statistics on users who saw having a "find prev" button as a problem, compared to the total number of atom users.

**Comment by lmj0011** [comment]
I'm not understanding what's hold up on putting this feature in. It would seem silly to make a plugin for something that should be native.

**Comment by redtopia** [comment]
Is there a plugin for this button? I would install it today and start using Atom.

**Comment by jonathanphz** [comment]
I agree that we need the Find previous button :(

**Comment by Buliwyfa** [comment]
me too big time saving

**Comment by orjanb-ne** [comment]
What is the update on this? Still no progress?

**Comment by dgarciap** [comment]
Could you add this button please? It is very useful and forcing the user to learn a shortcut for such a specific feature is not the best idea. 

It can be very annoying when you are working with more than one O.S. and Editors.

**Comment by tustin2121** [comment]
Time to start making a plugin for this, apparently.

**Comment by lmj0011** [comment]
I don't know when it happened, but the feature is added.

https://github.com/atom/find-and-replace#find-in-buffer


`shift+F3` will find Prev, however the button is not showing in my version of atom

```
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

![not_there](https://cloud.githubusercontent.com/assets/9396189/23696049/ac2db49c-03a7-11e7-8ffd-b6413ac0e4eb.png)

Is there a setting to show it?

**Comment by 50Wliu** [comment]
That screenshot is from a very old version of Atom.  It may be that the button used to exist and was then removed.  We should update those screenshots soon to reflect the latest UI changes.

**Comment by tigertontony** [comment]
+1 On having Find Previous

**Comment by jonathan-dejong** [comment]
Just browsed through the code and thought I'd mention that you can also hold shift while pressing "Find" to traverse upwards.

**Comment by toferj** [comment]
This should TOTALLY be a native feature. I don't understand the reluctance of anyone to back up their statements that they removed it because it was hardly ever clicked. Was there some kind of performance issue with leaving it in place? Who cares if no one clicks it very often. It's that time that you need it and it's missing, that you find yourself wasting time, searching the forums to find out what the hell is wrong with Atom that it's missing. Time that wouldn't be wasted if they just left the damn button in place. Who was it hurting exactly?

I understand that Atom is "hackable" and that someone has posted a way of adding this feature myself. Let me say again. I SHOULDN'T HAVE TO DO THIS. I already feel like I've wasted too much time looking for an answer to this. Atom may be hackable, but _I don't want to hack it_... I just want to _use it_. 

So I ask again... who was this hurting to leave the Find Prev. button in place?

**Comment by jonathanphz** [comment]
Just hold shift when clicking Find - it will go to previous :)

Calm down tiger

**Comment by lmj0011** [comment]
@toferj @joefitzgerald 

`ctrl+F`

enter pattern to find

then 

`F3` traverse finding foward

`shift+F3` traverse finding backwards


```
landan@lj-desktop:~$ atom -v
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
landan@lj-desktop:~$ 
```

**Comment by robsonsobral** [comment]
@lmj0011 , https://github.com/atom/find-and-replace/issues/453#issuecomment-155650983

**Comment by toferj** [comment]
My Atom is completely updated. I understand (after much searching) about holding Shift. STILL it seems the two responders MISSED THE POINT COMPLETELY. We shouldn't have to learn a keyboard shortcut. 

Nobody seems to want to answer what was wrong with having the button there. Who was it hurting exactly? I've counted three separate threads on this subject, all with multiple comments. That's A LOT of time wasted that could have been saved, but just LEAVING THE BUTTON WHERE IT WAS. 

So, what was the point of removing the button? Who did it help? What performance problem was solved by eliminating the onscreen cue to this functionality? It seems like it caused many people to waste time and resources asking about it, forking other projects, and generally being frustrated with the apparent lack of functionality when THEY COULD HAVE JUST LEFT WELL ENOUGH ALONE AND KEPT THE BUTTON IN PLACE. 

Can't ANYBODY see that?

And before someone comes back and says, "that's the great thing about open source... you can make the change yourself"... I don't want to, nor should I have to.

It's confusing to have the button not there. Just put it back where it belongs.

**Comment by jonathan-dejong** [comment]
@toferj I agree that there seems to have been really no point in removing it (and I also created a package which you can use instead of the core for now). 

I don't think there's anyone here defending the move to remove it, we're just trying to help each other. Note that there does not seem to be any core developer chiming in so far. Frankly I think the aggressive tone in your responses are the most offensive ones. Yeah sure, we shouldn't have to do anything because it shouldn't have been removed in the first place (according to us). But maybe you should also consider the fact that you get to use this awesome open source tool for free. 

Everyone is allowed to chime in and give their opinion but at least keep a civil tone and skip the Caps Lock.

**Comment by toferj** [comment]
@jonathan-dejong I don't see how my responses are aggressive, but just rather emphatic (how else to I add emphasis?). I wasted time trying to install your fork, but couldn't understand how to do it. I couldn't find your package when searching for packages under settings in Atom, and your page that you link to doesn't seem to have instructions to install (at least not ones I could follow).

I don't agree so far that this is an awesome tool. Free yes. Pretty good, sure. but awesome? I've just wanted to see recently what everyone was raving about, but honestly I don't see it. I'm finding too many things recently that just lead me to believe that Atom isn't as great as people claim. This is just one of the items. There are parts I like, but it just seems like a bad SublimeText clone.

**Comment by polarathene** [comment]
@toferj Your comments here do come off with an aggressive tone, that doesn't help move things forward in these communities, these aren't paid vendors you're trying to communicate with. 

If you need to add emphasis you can also use markdown for italics or bold, github provides helpful gui buttons if you're not fond of typing `*`.

Sublime is a paid product isn't it? You can use it free if you're ok with the nag adware. You don't have to deal with such on Atom, we can all agree that having an easy way to enable a prev button for this feature would be desired. You're just creating noise at this point. Atom is a great free and open source editor, it may require more time than others to configure, for some that is worth it. 

While I would very much like to see this feature addressed, it's not a game breaker, I've tried several editors(paid and free) and this is my favourite, you're free to have your opinion and use another editor if Atom does not satisfy your needs. Please stop creating noise, it notifies everyone subscribed to this issue with no value contributed. If you would like to support the issue, please thumbs up the first post if you haven't already.

Finally, I can't recall if it was related to this issue, but I remember a contribution for this or something similar in recent months. It was put on hold as Atom's internals for managing UI were being reworked that would change this up quite a bit. There is still hope to see this in future :)

---

**Please try to refrain from generating more noise on this issue in respect to others**

**Comment by alexandernst** [comment]
The `Previous` button was removed because, and I [quote](https://github.com/atom/find-and-replace/issues/322#issuecomment-66220653) @benogle

    It was intentional. Very very few people click that button. You can use the keyboard shortcut cmd-shift-g 
    instead.

Since then (Dec 9, 2014)

* this sole comment received 43 thumbs down emojis and 8 confused emojis.
* [5](https://github.com/atom/find-and-replace/issues/322) [new](https://github.com/atom/find-and-replace/issues/337) [threads](https://github.com/atom/find-and-replace/issues/453) [with](https://github.com/atom/find-and-replace/issues/467) [a](https://github.com/atom/atom/issues/7840) total of 38 participants and over 200 react emojis about the same topic were created.
* [a new package](https://atom.io/packages/find-and-replace-with-prev) just to bring this functionality back was created.

Judging by the amount of total effort wasted on this topic, I'd dare to say that it seems that not `very very few people click that button` .

Also, no other text editors or IDEs hide this button. Even further, browsers, text processors and pretty much any tool that allows searching within a text doesn't hide the "Previous" button. So why should Atom be different? Why should Atom break the UX that we all know and are used to?

There is plenty of space to bring back the button:

![](https://ibin.co/3PVSbatfHOk1.png)

**Comment by jonathan-dejong** [comment]
Just a heads up. Update my package https://atom.io/packages/find-and-replace-with-prev to the new version (published a minute ago) and you'll also have the replace prev button back. 

Hopefully the core contributors can consider copying over the code required. I should note that some themes does not seem to handle the extra buttons well, this is not because of the package but the theme. You can fix this yourself in your stylesheet if you want to keep the theme. 

Stay happy people and have a nice weekend!

**Comment by toferj** [comment]
Seems like making "noise" did a bit of good afterall... prior to that the last movement on this topic was several months ago. @jonathan-dejong you're good to have updated your package just to correct for the mistake the devs made "... breaking the UX that we all know and are used to.". Nobody should have had to do that, but you did. @jonathan-dejong++

**Comment by Aidolii** [comment]
Please add the button back. I used it.

**Comment by Blosberg** [comment]
I'd like to add my voice to the very clearly large number of users who strongly believe that there should be a "Find previous" button. It makes no sense for it to be removed. The fact that it's missing, while lots of esoteric buttons I never use are there is completely baffling.

1.  There's clearly sufficient space (I would gladly give up many of the buttons currently there if I needed to trade). 
2. The argument that it is seldom used does not seem to have any supporting evidence --perhaps it is used less often than "next", but only because users will frequently click "next" many times in sequence to scroll through a document. The times when I would click "previous" might be few in number, but they are very important.
3. Spending the last 20 minutes learning the keyboard shortcut for shift+Enter was a needless frustration. I'm certain that I will very quickly forget that shortcut and need to waste that time again in the future. This is unnecessary.

I'm new to using Atom, but seeing such a glaring omission is already making me regret the switch.

**Comment by UziTech** [comment]
@sadick254 this should be closed based on https://github.com/atom/find-and-replace/pull/1112#issuecomment-756297777
