### ISSUE TITLE
Replace All button disabled with no explanation

### ISSUE THREAD

**Issue by vemv-kantox** [atom/find-and-replace#491]
Button is disabled...

![image](https://cloud.githubusercontent.com/assets/12593885/9223250/a66777be-40f8-11e5-9bbf-142448cbf8e3.png)

No idea what the root cause is. No message appears when hovering the button either.

**Comment by izuzak** [comment]
Which query did you use for searching? A screenshot of the complete find and replace panel would be helpful.

**Comment by mnquintana** [comment]
Did you execute a search first? If you did, did that search return any results? See https://github.com/atom/atom/issues/8269#issuecomment-128709483

**Comment by deprint** [comment]
In the latest versions the buttons are disabled if there are no visible matches, which means:
a) Your search query cannot be found in the text editor
b) They added a package setting called "Live Search Minimum Characters" (Default: 3 characters). If your search string is shorter than 3 characters then the replace buttons will be disabled too.

b) is a problem for me because sometimes I have to replace small things (single characters, `\t`). I could set this setting to 0 or 1 characters but I don't need to see 500+ matches, I just want to replace them.

**Comment by vemv-kantox** [comment]
Oh, I needed to perform a search first. How could I guess that? :(

Proposed better UX: if no search was performed first, make the Replace All button do perform a search, after which the button becomes a "Confirm" button.

Or: when hovering the Replace All button, display a tooltip saying "You must perform the search before replacing!"

**Comment by benogle** [comment]
> Oh, I needed to perform a search first. How could I guess that? :(

Just out of curiosity, what would you expect the replace all button to do before performing a search if it were enabled?

**Comment by vemv-kantox** [comment]
To replace all occurrences. It's somewhat dangerous, but I'm sure the string query is precise enough, I can tell there will be no unexpected replacements performed.

Example: case-sensitive replace of `@foo_bar_baz`. Safe enough to replace without searching first.

**Comment by benogle** [comment]
> Example: case-sensitive replace of @foo_bar_baz. Safe enough to replace without searching first.

It used to do this just a couple releases ago, but people were [losing work](https://github.com/atom/find-and-replace/issues/331), so we've made it more explicit.

**Comment by vemv-kantox** [comment]
Don't save on replace, easy as that tbh. That's what the venerable Textmate used to do...

Then one would save all files by using the shortcut, as a confirmation.

You have multiple options to solve the usability issue in a safe way, would be great if you picked one!

**Comment by mnquintana** [comment]
> Don't save on replace, easy as that tbh. That's what the venerable Textmate used to do...

It's not really as easy as that - take a look at https://github.com/atom/find-and-replace/issues/331#issuecomment-126833569 for a thorough rundown of Replace All behavior across different editors.

**Comment by vemv-kantox** [comment]
Textmate behavior is incompletely described there.

When you replace everything in textmate, no confirmation box is raised **but** no files are saved **and** no tabs are opened. You "confirm" by saving all files with the adequate shortcut (command-option-S).

You could also go to files individually and save or undo, even if no tabs were opened.

Seems safe, powerful and useful to me.

**Comment by huphtur** [comment]
Running into the same problem here. Atom says it's unable to find a search string in the project, however the editor is highlighting several results.

![nnym9jd](https://cloud.githubusercontent.com/assets/469438/9440901/21f9d7e0-4a73-11e5-80de-f4fc716b1eb5.png)

What am I doing wrong here?

**Comment by adambuczynski** [comment]
> It used to do this just a couple releases ago, but people were losing work, so we've made it more explicit

@benogle I'd like to reopen this issue, because I feel the current way it works is lacking as well and isn't intuitive. In my opinion, the replace all button being disabled without explanation while you've entered a search and a replace term, is not really "more explicit" as you described.

A preferred approach in my opinion would be to keep the button enabled, but just show a confirmation dialog, with which you can confirm that you're going to do a replace all operation. I believe the dialog is currently in place, which is good, but it makes disabling the replace all button until you've done a search a bit overly redundant and cumbersome.
