### ISSUE TITLE
Find and replace across project processes all projects

### ISSUE THREAD

**Issue by maasha** [atom/find-and-replace#564]
I was expecting project wide find and replace to only process the current project, but it processes all projects? How can this be limited?

**Comment by izuzak** [comment]
You should be able to do that by specifying the root directory name of one of the projects as the file/directory pattern:

<img width="860" alt="screen shot 2015-10-20 at 17 11 59" src="https://cloud.githubusercontent.com/assets/38924/10611774/e699b92e-774d-11e5-8111-96d264f88989.png">

Let us know if that doesn't help.

**Comment by maasha** [comment]
Thanks, that should work, however, I am still a believer in the principle
of least astonishment
<https://en.wikipedia.org/wiki/Principle_of_least_astonishment> and find
the current behaviour astonishing. It would be nice with a setting,
possible a checkbox, for "find & replace" across all projects or current
project (which would be the project of the current file).


Cheers,


Martin

**Comment by izuzak** [comment]
> It would be nice with a setting,
> possible a checkbox, for "find & replace" across all projects or current
> project (which would be the project of the current file).

Thanks for the feedback and the suggestion, @maasha. Can you perhaps think of some edge cases which would need to be covered if such an approach was used (for example, if you have no files open), and how would you expect such edge cases to be handled?

Also wondering how @benogle and @maxbrunsfeld feel about this -- should we change the behavior of how find in project works in case there are multiple projects in Atom?

**Comment by maasha** [comment]
A thought for the case of no open files. The github package prompts you the
project if in doubt.

**Comment by dkts** [comment]
I find the current naming misleading, too. If the operation searches all projects by default, it should also be named "Search Project**s**".

+1 to @maasha's request for a real "Search (Current) Project" operation. That operation should restrict the search to the parent project of the currently edited file, and be unavailable if the currently edited file is not part of a project.

Javascript code isn't as easy to search by reference as in other languages, such as Java, so that programmers often use full-text search as a replacement for reference search in IDEs like Eclipse. The current behvaiour makes that "workaround" very tedious, especially when working with multiple projects and/or longer projects names.
