### ISSUE TITLE
Make default-state of flags for find/replace configurable

### ISSUE THREAD

**Issue by mnquintana** [atom/find-and-replace#565]
_From @goldsborough on October 20, 2015 19:15_

As of now, at least for me, every time I start Atom and hit cmd+f to do find/replace I have to manually set the regex + case-sensitivity flag. Can you please make the default-state of these flags configurable in the settings, or just store them from the last session? In Sublime the flags are remembered even after closing/restarting the application (i.e. really quitting, not just hiding). I find this really inconvenient in Atom right now. Sorry if there already is some mechanism of doing this, I just couldn't find anything for it.

_Copied from original issue: atom/atom#9232_

**Comment by benogle** [comment]
These defaults are configurable. They will work the first time a window is opened for a give directory:

* `find-and-replace.useRegex`
* `find-and-replace.caseSensitive`
* `find-and-replace.wholeWord`
* `find-and-replace.inCurrentSelection`

They are not in the settings view because they are not in the schema. But you can set them via:

```
"*":
  "find-and-replace": 
    useRegex: true
    caseSensitive: true
```
