### ISSUE TITLE
Auto-Close Search Panel Breaks "Replace in project"

### ISSUE THREAD

**Issue by dcalhoun** [atom/find-and-replace#612]
The "Close Project Find Panel After Search" setting currently breaks the ability to type a replacement value into the "Replace in project" field.

<img width="516" alt="replace-in-project" src="https://cloud.githubusercontent.com/assets/438664/11614829/dfc6e7b2-9c13-11e5-84b9-0fc67476e9b1.png">

### Behavior
As a user, I receive search results after submitting a term placed in the "Find in project" input, and I enter the first character of a replacement string in to the "Replace in project" input.

### Expected Outcome
Each search result updates displaying a red box around the original term and a green box containing the replacement string. The search panel remains **open and focused** allowing me to enter the second character of my replacement string.

### Current Outcome
Each search result updates displaying a red box around the original term and a green box containing the replacement string. The search panel remains **closes and loses focus** preventing me to enter the second character of my replacement string.

_Additional Notes_
This behavior continues each additional time I re-open the Find and Replace panel and insert an additional character into the "Replace in project" input. [Example screencast available here](http://quick.as/xkp7cZ2yX).

**Comment by pdxwolfy** [comment]
I am seeing the same issue. Find and Replace in Project is effectively unusable.

**Comment by cwilli34** [comment]
This is a pretty serious bug.  You can't even use the find-and-replace feature in the "Find in project" panel.  This could even be a reason for a user to switch editors.  Is there any update on this?

**Comment by 50Wliu** [comment]
No official updates yet.  Anyone is free to submit a PR for it.

**Comment by ungb** [comment]
This is still an issue on 1.15.0 of atom.

See Gif:
![findreplace](https://cloud.githubusercontent.com/assets/5624870/24275857/da6e7b30-0fef-11e7-866f-a9f95f5a3fb9.gif)


If you have the box uncheck(default behavior) you don't see this issue.

**Comment by smashwilson** [comment]
I've fixed this in #923, released it as v0.209.3, and merged it into Atom master :smile: There were a few edge cases and related behavior that I encountered along the way that I just kind of picked what felt right to me to resolve... but because I don't use this setting myself, I don't want to say with confidence that my decisions will feel natural to _everyone_, so, weigh in if you disagree:

* If you trigger a search by pressing `core:confirm` with the search input focused, and the search results are cached, the find-and-replace panel _is_ dismissed. (It felt weird to me to have the hide behavior modified by state outside of the panel itself.)
* If you trigger a search with an _empty_ search input box, we _do not_ dismiss the find-and-replace panel, because you haven't actually searched for anything yet. (Note that you can still dismiss it with `core:cancel`.)

**Comment by dcalhoun** [comment]
@smashwilson the second behavior makes sense to me.

With the first, what relevancy does the "the search results are cached" have on the behavior? How would this behavior be different from a normal search?  What "outside" state are you referring to? Sorry, I didn't follow your train of thought.
