### ISSUE TITLE
Permit searching across underlying token?

### ISSUE THREAD

**Issue by gjtorikian** [atom/find-and-replace#676]
I have a feature request that I don't mind putting in the work to write a PR for. I want to make sure it's both desired and hasn't been discussed before doing that, though.

Atom provides underlying token information about items it's syntax highlighted:

``` html
<span class="support class ruby">Event</span>
```

I'd like to modify `find` so that I can query against these underling tokens. That is, if I search for a case-sensitive whole-word phrase like `Event`, I can specify that I only want results indicating the `Event` class—not `Event`s of type `comment` or anything else.

is this feasible? I'm not sure if `find` takes a look at the raw buffer, or if it's possible to determine the DOM of a piece of matched text.

**Comment by lee-dohm** [comment]
Because the entire text of the file is not in the DOM necessarily for performance reasons, it won't work through the DOM. Also, the Atom API doesn't have a way to detect the scopes that apply to a range, [only a point](https://atom.io/docs/api/latest/Cursor#instance-getScopeDescriptor). Going behind the scenes, you might be able to cobble something together that compares the selections that get generated by a find operation to the [`TokenizedBuffer`](https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee). I suspect there would be a lot of edge cases though.

Wouldn't the symbols-view work for most operations of this type?

**Comment by gjtorikian** [comment]
I never knew `symbols-view` worked across the project. Thanks!

**Comment by lee-dohm** [comment]
You're welcome! I'm glad that I could help :grinning:
