### ISSUE TITLE
Whole Word find does not work with symbols.

### ISSUE THREAD

**Issue by duanechew** [atom/find-and-replace#708]
I've been trying to find all instances of the git merge conflict marker "=======". If I do a normal find, the results will include numerous comments that also use the "=" symbol repeatedly, so I needed to do a Whole Word find to uncover only those instances of exactly 7 ='s, but I get no results.

**Comment by lee-dohm** [comment]
I'm not sure I'm understanding the problem correctly. Can you include a sample file and some steps to reproduce the issue?

**Comment by duanechew** [comment]
If I were to perform a find for "=======", the results would include not only "=======" but also:
"======================"
or 
"================="
or
"===================================".

But I really only want to find these: "=======". So I try to do a whole word search instead, but that returns no results.

It's possibly I'm not understanding how whole word search works, but my understanding was it was supposed to return only EXACT matches of the search term. Does that make sense?

**Comment by lee-dohm** [comment]
Yes, it does, thank you for the extra explanation. I created two sample files:

**Test**

```
test
testtest
testtesttest
```

**Test Symbols**

```
=======
==============
=====================
```

They are the same pattern repeated once, twice and three times. When I search for `test` with Whole Word enabled on the first file, the first line is found. When I search for `=======` with Whole Word enabled on the second file, no matches are found.

Underneath the covers, Whole Word is implemented as wrapping the search text in `\b` tokens and performing a regular expression search. Since `\b` matches "word" boundaries, in other words the transition from word to not-word and vice versa, that is why it is failing your expectations here. There is no transition to or from a word to match against.

As a workaround, you could use something similar for your purposes:

1. Set the Find text to: `[^=]=======[^=]`
1. Disable Whole Word
1. Enable Regular Expressions
1. Execute the search

This should match your expectations.

-----

The pattern I supplied in the workaround above essentially breaks down to "not an =, followed by seven =, followed by not an =".

**Comment by duanechew** [comment]
Oh great! Thanks for your help!
