### ISSUE TITLE
Search simply doesn't work at all.

### ISSUE THREAD

**Issue by tenten8401** [atom/find-and-replace#819]
### Description

Search simply does not work, it may be after a certain line number, I'm unsure, but it's always when I'm editing code.

### Steps to Reproduce

1. Open Atom in safe mode `atom --safe`
1. Open [csgo_english.txt](https://github.com/atom/find-and-replace/files/617843/csgo_english.txt)
1. Open the `find-and-replace` panel
1. Enter any search term that exists in the file
1. Expected: search term to be found. Actual: No results are found
1. Change encoding to `UTF-16 LE`
1. Expected and actual: search term is found

**Expected behavior:**
It should be able to find what I ask it to when it exists in the file regardless of encoding.

**Actual behavior:**
It claims there are no results found when UTF-8 encoding is used.

**Screenshots:**
![image](https://cloud.githubusercontent.com/assets/6174343/20641071/9686fc78-b3bd-11e6-8de3-4758f0eee41a.png)

### Versions
Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python
git
visual studio 2015

**Comment by thomasjo** [comment]
As mentioned in https://github.com/atom/atom/issues/13333#issuecomment-263068190, this is almost surely caused by our limitations with large files. I'm not entirely sure if this problem/limitation specifically originates in the package, or in core due to markers being disabled.

Regardless, I think we should deal with this in a more user-friendly manner; if we disable searching for large files, we should inform the user instead of silently failing.

/cc @atom/feedback

**Comment by maxbrunsfeld** [comment]
This isn't the expected behavior, though our search has been known to perform poorly on insanely long files. How large is the file? Can you share a file that is causing this behavior for you?

**Comment by tenten8401** [comment]
[csgo_english.txt](https://github.com/atom/find-and-replace/files/617843/csgo_english.txt)
^ This is the file I was using in the screenshot

**Comment by Ben3eeE** [comment]
I tested with this file and was able to reproduce the behavior. I noticed the file starts with two strange characters so I went into the `Encoding Selector` chose auto detect which selected the `UTF-16 LE` encoding. Search now works.

![image](https://cloud.githubusercontent.com/assets/1058982/20700126/b5e34446-b60b-11e6-891b-ad62c4abed89.png)
![image](https://cloud.githubusercontent.com/assets/1058982/20700143/d838b6ca-b60b-11e6-892f-f086f9a5ae15.png)

**Comment by tenten8401** [comment]
Can confirm. Switching encoding to auto worked.

Why isn't encoding auto by default when opening files?

**Comment by Ben3eeE** [comment]
@tenten8401 For auto detecting encoding when opening new files we have https://github.com/atom/encoding-selector/issues/24. You may want to subscribe there for updates.

**Comment by lee-dohm** [comment]
Possibly related: #751

**Comment by maxbrunsfeld** [comment]
This is the expected behavior. The file is being decoded with the wrong encoding, so the text actually does not contain the string you are searching for: `SFUI`. Between every letter, there is a null byte.

As @Ben3eeE said, please subscribe to https://github.com/atom/encoding-selector/issues/24 for updates on auto-detecting encodings by default.

**Comment by matanster** [comment]
Are you positive about Atom not stopping the search early when large files are present in the file/directory?
