### ISSUE TITLE
Find without Replace

### ISSUE THREAD

**Issue by jcuenod** [atom/find-and-replace#831]
I'd really like to be able to open the `find` bar without having `replace` permanently beneath it (`ctrl`+`f` vs `ctrl`+`h` on some editors).

The main reason I want to see this is for the vertical real estate.

**Comment by lee-dohm** [comment]
Thanks for contributing!

I have passed along the information to the maintainers team for review after the holidays. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. 

Thanks again for reaching out :grinning:
