### ISSUE TITLE
Cancel, stop at 1000 matches, stop at 60 seconds, background task, anything.

### ISSUE THREAD

**Issue by MichaelJCole** [atom/find-and-replace#848]
Find and replace freezes.  When find and replace freezes, I know I don't want the results.

How about a cancel button?  Or Max-results config option?  Or max-time config option?

How can I stop a search that is taking too long?  Search is absolutely a core feature.

Thank you

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
