### ISSUE TITLE
find-next-selected(Ctrl-F3) command works only after calling find(Ctrl-f) command initially

### ISSUE THREAD

**Issue by Si7ius** [atom/find-and-replace#857]
### Description of problem

I opened some file with Atom text editor. After that I tried to find word that cursor is standing in using `Ctrl-F3`. But it didn't work. I call find window (`Ctrl-f`) and closed it. After this operation I could use `Ctrl-F3` command freely.

* [ ] `find-next-selected` command should work at start although `find` command initially called

**Comment by rsese** [comment]
Thanks for reaching out!  As mentioned in https://github.com/atom/find-and-replace/issues/864, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

In particular, see this forum post that discusses the same issue:

https://discuss.atom.io/t/find-next-behavior/8759/2

And this package is referenced that seems to implement the behavior you want:

https://atom.io/packages/find-selection
