### ISSUE TITLE
Basic Occurrence Highlighting is Missing from Core (re-opening after three years)

### ISSUE THREAD

**Issue by CollinChaffin** [atom/find-and-replace#881]
Before someone quickly references the other (still open) but locked issue (hence why I'm opening this) that seemed to have been locked in conjunction to some pretty sketchy and arrogant comments (and closes or locks this issue)- I ask that the issue I am referencing be re-opened or you at least consider the request.  Why?  Simple, It is 2017.  We began requesting this very basic feature in 2014.  DEVs at the time did not want to even hear how many users wanted it.  Since then, your loyal users are spreading the word about the Atom editor (me included), but that means that OVER THREE YEARS have passed since we asked for this basic feature that frankly every other editor on the planet except Atom does has right out of the box.

Issue #138 is what I am referring to and again I am requesting an unlock here because it is locked and I cannot post there under that issue, and it was frankly very arrogantly locked with no care for the users that support this team and Github.  A senior manager of the Atom DEV team should have reviewed the statements made by the (then) active DEVs in issue #138 by now (or I would ask they do now) that flat out state that simply leaving the ability enabled (like every other issue) for a million of your product users to very respectfully potentially all +1 an issue to **_tell you, the developers, that they need a feature added or fixed_** - was somehow "problematic" and "became too noisy"......WHAT?!?  Too "noisy"!?!  You're the same people that put Github here AND ADDED THAT VERY FEATURE to allow us to +1 issues and their comments to indicate shared importance, and now when it's your own product that folks begin to come in droves to +1 to ask you to frankly fix to bring up to the level of the most BASIC editors out there (I mean it's embarrassing now since even NPP does this without any plugins in a single 2 megabyte executable) and the solution is to put up the virtual "hand" to your users and lock the issue?

In any of the DEV teams I've worked with in any of the companies for which I've consulted over the last 30 years, I would have **_lost my job_** had I treated the consumers of my products/work in that fashion.  The only place I have been seeing this recently is in open source software and perhaps it is just because it is a free effort; but free or not, if you don't care about those consuming your product then you are really just developing the product for your own personal use - and then that should be made clear from the get-go.  Since Atom started as Github's internal editor as I understand it, perhaps that is/was the issue but clearly Atom WAS released to the the public masses for consumption, so now you DO need to listen when the masses ask for support, not lock issues and tell your users to go away.

So it has now been 3 years and while other Atom core development apparently took place, all those same users (me included) were out spreading the word and evangelizing the Atom editor but the Atom team chose not to apparently even attempt to work on this issue.   The really bad news is this forced your users to hack together another dozen+ conflicting addons as you kept the proverbial hand up to our faces.  I think every one of those addons state right from the getgo they had to create what should be a core feature and most even acknowledge they are a "hack" that (because it is not within the core codebase) winds up being "hacky" and is an overall poor user experience.  I don't want a "hacky" editor or a poor user experience;  I mean I didn't have it that bad with NPP or VSCode so I shouldn't with Atom.

To test whether your user-base still shares my strong need for Atom to support basic selection highlighting in the core, I request that you would kindly consider simply unlocking open issue #138 for comments and allow collaboration to perhaps get it done.

**Comment by lee-dohm** [comment]
Hello, @CollinChaffin. I can totally appreciate your frustration because this situation frustrates me as well though for different reasons.

You're right that we haven't implemented this feature. You are absolutely right that we have continued to do dev work on other things that we considered to be higher priority than this feature. You're even right that it is now 2017. It has been three years since #138 has been opened. It has also been three years since the [highlight-selected package](https://atom.io/packages/highlight-selected) was initially released. Perhaps it was "hacky" in the beginning but over the past three years it has become very polished and well-built. I know because I've been using it and recommending it [for just about three years.](https://discuss.atom.io/t/lights-the-same-word-in-document/11214)

On the topic of customers, in the open source model there are no customers, there are only collaborators. Some people collaborate by writing documentation, some people collaborate by filing issues with bugs or enhancement suggestions, some people collaborate by writing code, some people collaborate by building packages or extensions to other open source projects, some people collaborate by offering to help with answering people's questions on message boards, issues ... and the list goes on and on. Open source is about everyone getting together to "move the ball forward". Being a customer doesn't help move the ball forward because no money changes hands. We aren't asking for money and we don't want people to give us money. We want people to **work with us** to make something awesome. So I would ask you the question, "How do you want to help move the ball forward here?" Are you going to contribute to the highlight-selected package to make it less "hacky"? (Though I would contend that all that is needed there is to take the word "hacky" out of the README.) Or are you going to work with the maintainer of highlight-selected to create a Pull Request to merge the functionality of highlight-selected into Atom itself? Or something else that I admittedly haven't thought of?

Atom was released as open source and designed to be extensible because the team knew that they would be unable to design, build and maintain all of the features that everyone would want, both from the perspective of simply not having enough people and also from the perspective of not having sufficient familiarity with or expertise in all of the various workflows, frameworks or tools that developers from all over the world employ. This model has been validated time and again by packages such as highlight-selected being built and made available to the Atom community to offer the features that people want without being blocked by the lack of manpower within the core group of maintainers. So it is frustrating to me that all of our efforts and hard work in creating an API that allows this to happen is completely discounted by people that seemingly are quibbling over an implementation detail. The feature that you want is implemented, supported and has been for three years.

Yes, we have locked the conversation on the issue because we, the people that offer this software to the world for free, many of us by volunteering our time, our effort and our expertise, without pay, without recompense and often seemingly (again by people claiming to be customers) without appreciation, needed to do so to control the influx of notifications coming from the community _so that we could simply have the time in the day to **read** all of the feedback we are getting from the community._ The community that we care so much about that we take the time to read absolutely everything they write to us, no matter how gruff, no matter how disparaging, no matter how frustrated and antagonistic. So yes, at some very rare occasions, we have made the decision to lock comments on issues when we felt, in order to manage our time better, the discussion that was generating notifications was no longer productive or informative for us ... the people that have chosen to take on this job. I don't feel that is arrogant of us in any way, that is us being realistic about what we can do and taking steps to ensure that we can continue to do it.

I can understand that you may feel like you aren't being listened to. Hopefully the time that I have taken to write this reply has disabused you of that notion. We obviously don't agree on the basic philosophy of managing an open source project but that doesn't mean that we can't find some common ground. I hope that we can find that common ground whatever it may be.

------

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com (or if you would like to discuss this specific topic in more detail, you can email me directly at lee-dohm@github.com).
