### ISSUE TITLE
Multiline search

### ISSUE THREAD

**Issue by kirkstrobeck** [atom/find-and-replace#892]
Cannot perform a search and replace across a project with multiple lines and spaces.

ie. search for 

```js
/*
  kdsjfhdskjf
          ldsk       dlkfjslfkjs


*/
var a = 1;
```

replace with 

```js
/*
  kdsjfhdskjf
          ldsk       dlkfjslfkjs hey there


*/
var a = 1;
```

I believe it trims each line before performing the search when it should have identical visible and invisible characters. Note: Sublime text can do this.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
