### ISSUE TITLE
Find in project: canceling the task

### ISSUE THREAD

**Issue by GithubGY** [atom/find-and-replace#921]
Is there any way of canceling a search other than killing the Atom's process?

**Comment by rsese** [comment]
Thanks for reaching out!  I don't believe so and there's an existing enhancement request for this functionality:

https://github.com/atom/find-and-replace/issues/310

You can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
