### ISSUE TITLE
Disabling and re-enabling the package makes select-next command select two next occurences of word

### ISSUE THREAD

**Issue by fredrikekelund** [atom/find-and-replace#950]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As reported in https://github.com/mehcode/atom-project-plus/issues/98, after programatically disabling and then re-enabling this package, the `find-and-replace:select-next` command will select the next two occurences of the highlighted word. Repeating the disable/re-enable procedure will select the next three occurences. Do it again and it will select the next 4, and so on.

The reason that [atom-project-plus](https://github.com/mehcode/atom-project-plus) disables/re-enables this package is that it otherwise, find-and-replace won't be able to search any file in the newly opened project.

I don't know which one of these issues is easier to fix, but my bet is on the former.

### Steps to Reproduce

1. Install atom-project-plus
2. Open a project normally in Atom
3. Switch projects using atom-project-plus
4. Highlight a word and trigger the `find-and-replace:select-next` command

**Expected behavior:**
The next occurence of the word should be selected

**Actual behavior:**
The two next occurences of that word is selected

**Reproduces how often:**
Every time

### Versions
```
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

find-and-replace: 0.208.3
```

### Additional information

Once again, this seems to be triggered by disabling and re-enabling the find-and-replace package. The relevant code can be found [here](https://github.com/mehcode/atom-project-util/blob/master/index.js#L215-L217)

**Comment by Ben3eeE** [comment]
@fredrikekelund Thank you so much for this report :heart: 

/cc: @rsese and https://github.com/atom/find-and-replace/issues/936 :tada:

**Comment by alexcroox** [comment]
Well done for finding the problematic package! This has been driving me crazy for months

**Comment by GitLiamuk** [comment]
Is there an update on this? Rely on the Ctrl+D shortcut heavily at work and it's really slowing me down.

**Comment by Sofianio** [comment]
This happened to me too after installing project-plus ... any available fixes?
Also: It would be nice to have the "select all occurrences" on a shortcut like cmd+e

**Comment by zedtux** [comment]
Looking for an update too, like @GitLiamuk I'm using it heavily at work and home and is pretty hard to handle it.

**Comment by fredrikekelund** [comment]
As reported in https://github.com/mehcode/atom-project-plus/issues/98#issuecomment-384704865, a variation is this issue has started showing up again. This time around however, the find-and-replace panel doesn't show up at all when you press Cmd+F.

**Comment by Ben3eeE** [comment]
@fredrikekelund I can not reproduce the behavior you describe by enabling and disabling the `find-and-replace` package. If you can reproduce this by enabling and disabling the `find-and-replace` package then please open a new issue.

If you can only reproduce it when switching projects with project-plus then it would appear that it's a bug in that package.  It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
