### ISSUE TITLE
[Feature request] project find and rename options for files and folders

### ISSUE THREAD

**Issue by Billybobbonnet** [atom/find-and-replace#957]
I am looking for a find and rename feature. It would allow to find and replace or rename files, folders, and file content to replace one term by another, exactly like the project find feature works, but in a version extended to file and folder names.

I could be one or two buttons in the search options:
- Include folder names
- Include file names.

I looked into the packages and couldn't find any matching my needs. Since I think it would be a great base feature, I thought it was worth opening a ticket.

**Comment by Berzeg** [comment]
@rsese @lee-dohm

I think it would be useful for scenarios where files/directories derive their name from a class. I'd be interested in creating a PR for the issue if this is a feature the atom team would like to have.
Any thoughts?

e.g.  before find and replace:
```
SomeComponent/
|-- SomeComponent.js
|-- SomeComponentItemA.js
|-- SomeComponentItemB.js
```

```
// SomeComponent.js

class SomeComponent {
  ...
}

export default SomeComponent;
```

after `/SomeComponent/SomeOtherComponent/gim`:

```
SomeOtherComponent/
|-- SomeOtherComponent.js
|-- SomeOtherComponentItemA.js
|-- SomeOtherComponentItemB.js
```

```
// SomeOtherComponent.js

class SomeOtherComponent {
  ...
}

export default SomeOtherComponent;
```

---

### Mockups

A complete implementation could look something like this:

![new_ui](https://user-images.githubusercontent.com/2348447/46031908-303b8780-c0c8-11e8-899d-849b7f35c4f0.png)

The icon for the "include file-tree names" option could look something like this:

![standalone_icons_2x](https://user-images.githubusercontent.com/2348447/46031975-66790700-c0c8-11e8-92bb-9c60e3a7c8a2.png)

**Comment by rsese** [comment]
I don't want to speak for Lee, but though I think the functionality could definitely be useful for some folks (and the "scenarios where files/directories derive their name from a class" case is pretty interesting), I also think it's outside the scope of this package but would be a neat community package.

**Comment by lee-dohm** [comment]
Thanks very much for the feedback and ideas.

I agree with @rsese. I feel this is definitely out of scope for the find-and-replace package and would be best implemented separately. I think this would be a very interesting idea for a community package, especially if it could offer to normalize to standard naming conventions for popular languages and frameworks and offer a way to define naming conventions of one's own.

Since this isn't something that the Atom team is going to take on, I'm going to close this. Thanks very much for the awesome ideas and your interest in making Atom better!
